[package]
name = "arch"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv-rt = { version = "0.12.2", features = ["s-mode"] }
riscv = "0.11.1"
sbi = "0.2.0"
